name: "解题分享 (Solution Submission)"
description: "分享解题思路。请在标题中直接填写练习编号，例如：[解题分享] 43"
title: "[解题分享] "
labels: ["solution", "community"]
assignees:
  - ""
body:
  - type: textarea
    id: solution-code
    attributes:
      label: "您的答案 (Your Solution)"
      description: "请将您的 Python 代码粘贴到此处。"
      render: python
      placeholder: |
        def some_function():
            # Your code here
            pass
    validations:
      required: true
  - type: textarea
    id: thought-process
    attributes:
      label: "解题思路 (Thought Process)"
      description: "（选填）可以分享一下您的解题思路、您是如何考虑这个问题的、以及为什么您选择这样实现。"
  - type: textarea
    id: additional-context
    attributes:
      label: "其他信息 (Additional context)"
      description: "（选填）如果您有任何其他想补充说明的信息，请在此处填写。"
